# Generated by Django 4.1 on 2023-06-15 19:29

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Calibrar',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('voltajeEstable', models.FloatField()),
            ],
        ),
        migrations.CreateModel(
            name='Fecha',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha', models.DateField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='Usuario',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=200)),
                ('correo', models.EmailField(max_length=200)),
                ('contra', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Sensor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('voltaje', models.FloatField()),
                ('esInicial', models.BooleanField(default=False)),
                ('calibrar', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='AppBendingLoss.calibrar')),
                ('fecha', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='AppBendingLoss.fecha')),
                ('usuario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='AppBendingLoss.usuario')),
            ],
        ),
    ]
