# Generated by Django 4.2.2 on 2023-07-04 07:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("AppBendingLoss", "0001_initial"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="sensor",
            name="esInicial",
        ),
        migrations.AddField(
            model_name="sensor",
            name="indice",
            field=models.IntegerField(default=0),
            preserve_default=False,
        ),
    ]
